### PR TITLE
add --mount option

### PR DESCRIPTION
**Pull request by Songmu**

### CODE REVIEW

**Comment by Songmu** [comment]
@book How about my 3 pull requests? (#3 #4 #5)

These are basic and necessary features for Wallflower.

Wallflower is very important for [Riji](https://metacpan.org/release/Riji), which is blog engine I made and heavily depend on wallflower for static site generation.

**Comment by book** [comment]
Sorry, I haven't had time to look at them yet. I'll try to find time soon.

Thanks for the patches and the reminder.

**Comment by Songmu** [comment]
Thank you for your response. I wait your review slowly.

**Comment by book** [comment]
Applied as bc8dad73f720620293276b71603a17386d0a2eac.

I made some modifications to generate the mounted app directly at object creation time. Plus some changes to the English text.

Many thanks. I will follow up on the other PR and do a release before Sunday.

**Comment by Songmu** [comment]
Thank you!

**Comment by book** [comment]
As a user of Wallflower, maybe you could add a review at CPAN Ratings:
<http://cpanratings.perl.org/dist/App-Wallflower>.

Thanks.

**Pull request closed without merging**
